export const ERROR_CODES = {
  VALIDATION_ERROR: "E001",
  NOT_FOUND: "E002",
  DATABASE_FAILURE: "E003",
  INTERNAL_ERROR: "E500",
  TRANSACTION_FAILED: "E004",
  BATCH_INSERT_FAILED: "E005",
  PAGINATION_FAILED: "E006",
};
